import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { DatabaseSync } from "node:sqlite";
import {
  ITEMS,
  MAX_BASE_LEVEL,
  MAX_LEVEL,
  MAX_PARTY,
  MAX_WORKERS,
  PAL_SPECIES,
  RESOURCES,
  WORLD_HEIGHT,
  WORLD_WIDTH,
  type Item,
  type Resource,
} from "@petgame/shared";

export interface SavedPal {
  id: string;
  speciesId: string;
  level: number;
  xp: number;
  assignment: "" | "follow" | "work";
}

/** Everything that survives leaving the game, keyed by the device token. */
export interface Profile {
  name: string;
  pals: SavedPal[];
  base: { x: number; y: number } | null;
  baseLevel: number;
  resources: Record<Resource, number>;
  items: Record<Item, number>;
  /** When the profile was last saved (ms since epoch); drives offline production. */
  savedAt: number;
}

export interface ProfileStore {
  load(token: string): Profile | undefined;
  save(token: string, profile: Profile): void;
  close(): void;
}

/** Tokens are random ids generated by the client (crypto.randomUUID). */
export function isValidToken(token: unknown): token is string {
  return typeof token === "string" && /^[A-Za-z0-9-]{16,64}$/.test(token);
}

export function emptyProfile(name: string): Profile {
  return {
    name,
    pals: [],
    base: null,
    baseLevel: 1,
    resources: { wood: 0, stone: 0, berries: 0 },
    items: { greatBalls: 0, snacks: 0 },
    savedAt: 0,
  };
}

/** SQLite-backed store (node:sqlite, no extra dependency). */
export class SqliteStore implements ProfileStore {
  private db: DatabaseSync;

  constructor(path: string) {
    if (path !== ":memory:") mkdirSync(dirname(path), { recursive: true });
    this.db = new DatabaseSync(path);
    this.db.exec(`CREATE TABLE IF NOT EXISTS profiles (
      token TEXT PRIMARY KEY,
      data TEXT NOT NULL,
      updated_at INTEGER NOT NULL
    )`);
  }

  load(token: string): Profile | undefined {
    const row = this.db.prepare("SELECT data FROM profiles WHERE token = ?").get(token) as { data: string } | undefined;
    if (!row) return undefined;
    try {
      return sanitizeProfile(JSON.parse(row.data));
    } catch {
      return undefined;
    }
  }

  save(token: string, profile: Profile): void {
    this.db
      .prepare(
        `INSERT INTO profiles (token, data, updated_at) VALUES (?, ?, ?)
         ON CONFLICT(token) DO UPDATE SET data = excluded.data, updated_at = excluded.updated_at`,
      )
      .run(token, JSON.stringify(profile), Date.now());
  }

  close(): void {
    this.db.close();
  }
}

const DEFAULT_DB = join(dirname(fileURLToPath(import.meta.url)), "../../data/petgame.db");

/** Opens the store at PETGAME_DB (":memory:" for tests), defaulting to packages/server/data. */
export function openStore(): ProfileStore {
  return new SqliteStore(process.env.PETGAME_DB ?? DEFAULT_DB);
}

/** Drops anything malformed or out of range from stored data. */
export function sanitizeProfile(raw: unknown): Profile | undefined {
  if (!raw || typeof raw !== "object") return undefined;
  const r = raw as Record<string, any>;
  const species = new Set(PAL_SPECIES.map((s) => s.id));
  const num = (v: unknown, min: number, max: number, fallback: number) =>
    typeof v === "number" && Number.isFinite(v) ? Math.min(Math.max(v, min), max) : fallback;

  const pals: SavedPal[] = [];
  const ids = new Set<string>();
  let following = false, workers = 0;
  for (const p of Array.isArray(r.pals) ? r.pals : []) {
    if (pals.length >= MAX_PARTY) break;
    if (!p || typeof p.id !== "string" || !/^[A-Za-z0-9-]{1,40}$/.test(p.id) || ids.has(p.id) || !species.has(p.speciesId)) continue;
    let assignment: SavedPal["assignment"] = p.assignment === "follow" || p.assignment === "work" ? p.assignment : "";
    if (assignment === "follow" && following) assignment = "";
    if (assignment === "work" && workers >= MAX_WORKERS) assignment = "";
    if (assignment === "follow") following = true;
    if (assignment === "work") workers++;
    ids.add(p.id);
    pals.push({
      id: p.id,
      speciesId: p.speciesId,
      level: Math.round(num(p.level, 1, MAX_LEVEL, 1)),
      xp: Math.round(num(p.xp, 0, 1e9, 0)),
      assignment,
    });
  }

  const base =
    r.base && typeof r.base === "object"
      ? { x: num(r.base.x, 0, WORLD_WIDTH, WORLD_WIDTH / 2), y: num(r.base.y, 0, WORLD_HEIGHT, WORLD_HEIGHT / 2) }
      : null;
  const resources = { wood: 0, stone: 0, berries: 0 } as Record<Resource, number>;
  for (const key of RESOURCES) resources[key] = Math.floor(num(r.resources?.[key], 0, 1e9, 0));
  const items = { greatBalls: 0, snacks: 0 } as Record<Item, number>;
  for (const key of ITEMS) items[key] = Math.floor(num(r.items?.[key], 0, 1e6, 0));
  const name = typeof r.name === "string" ? r.name.slice(0, 16) : "";
  const baseLevel = Math.round(num(r.baseLevel, 1, MAX_BASE_LEVEL, 1));
  const savedAt = num(r.savedAt, 0, Date.now(), 0);
  return { name, pals, base, baseLevel, resources, items, savedAt };
}
